"""Disposable SQLite and VM-state lifecycle used by recovery integration tests."""

# ruff: file-ignore[suspicious-xml-etree-import, suspicious-xml-element-tree-usage, start-process-with-partial-path, raise-vanilla-args, raw-string-in-exception]
# XML below is a fixed local fixture generated by its adjacent test.
from __future__ import annotations

import io
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tarfile
import xml.etree.ElementTree as ET
from pathlib import Path


def execute(phase: str) -> None:
    """Run a phase against disposable test paths only.

    Raises:
        ValueError: The phase or recovered snapshot is invalid.

    """
    source = Path(os.environ["FIXTURE_SOURCE"])
    export = Path(os.environ["RECOVERY_EXPORT"])
    target = Path(os.environ["RECOVERY_TARGET"])
    if phase == "export":
        with (
            sqlite3.connect(source / "app.sqlite") as original,
            sqlite3.connect(export / "app.sqlite") as snapshot,
        ):
            original.backup(snapshot)
        shutil.copytree(source / "vm", export / "vm")
    elif phase == "backup":
        archive = io.BytesIO()
        with tarfile.open(fileobj=archive, mode="w") as bundle:
            for entry in sorted(export.iterdir()):
                bundle.add(entry, arcname=entry.name)
        subprocess.run(
            [
                "restic",
                "backup",
                "--stdin",
                "--stdin-filename",
                "application.tar",
                "--tag",
                "application-fixture",
            ],
            input=archive.getvalue(),
            check=True,
            capture_output=True,
        )
    elif phase == "recover":
        snapshots = json.loads(
            subprocess.run(
                [
                    "restic",
                    "snapshots",
                    "--json",
                    "--tag",
                    "application-fixture",
                    "--latest",
                    "1",
                ],
                capture_output=True,
                check=True,
            ).stdout
        )
        if len(snapshots) != 1:
            raise ValueError("Expected one fixture snapshot")
        archive = subprocess.run(
            ["restic", "dump", snapshots[0]["id"], "/application.tar"],
            capture_output=True,
            check=True,
        ).stdout
        with tarfile.open(fileobj=io.BytesIO(archive)) as bundle:
            bundle.extractall(export, filter="data")
    elif phase == "restore":
        shutil.copytree(export, target, dirs_exist_ok=True)
    elif phase == "check":
        with sqlite3.connect(target / "app.sqlite") as database:
            assert database.execute("PRAGMA integrity_check").fetchone() == ("ok",)
            assert database.execute(
                "SELECT name, value FROM records ORDER BY name"
            ).fetchall() == [("after-checkpoint", 42), ("initial", 7)]
        vm = ET.parse(target / "vm/domain.xml").getroot()
        assert vm.findtext("uuid") == "de305d54-75b4-431b-adb2-eb6b9e546014"
        assert (
            target / "vm/firmware.fd"
        ).read_bytes() == b"fixture-firmware-generation-2"
        assert (target / "vm/tpm/state").read_bytes() == b"fixture-tpm-generation-2"
        assert (
            target / "vm/disk.raw"
        ).read_bytes() == b"fixture-guest-persisted-generation-2"
    else:
        raise ValueError(phase)


if __name__ == "__main__":
    execute(sys.argv[1])
