#!@bash@
# shellcheck shell=bash
set -euo pipefail

@mkdir@ -p @configDir@ @dataDir@/data @dataDir@/meilisearch @stateDir@
@chmod@ 700 @dataDir@
nextauth_secret=""
meili_master_key=""
if [ -f @envFile@ ]; then
  nextauth_secret="$(@grep@ -E '^NEXTAUTH_SECRET=' @envFile@ | @head@ -n1 | @sed@ 's/^NEXTAUTH_SECRET=//' || true)"
  meili_master_key="$(@grep@ -E '^MEILI_MASTER_KEY=' @envFile@ | @head@ -n1 | @sed@ 's/^MEILI_MASTER_KEY=//' || true)"
fi
[ -n "$nextauth_secret" ] || nextauth_secret="$(@openssl@ rand -base64 36)"
[ -n "$meili_master_key" ] || meili_master_key="$(@openssl@ rand -base64 36)"
umask 0077
tmp_env="$(@mktemp@ @configDir@/.env.XXXXXX)"
{
  printf '%s\n' '# Generated by Home Manager. Secrets are preserved across rebuilds.'
  @cat@ @environmentDefaults@
  printf 'NEXTAUTH_SECRET=%s\n' "$nextauth_secret"
  printf 'MEILI_MASTER_KEY=%s\n' "$meili_master_key"
} >"$tmp_env"
@mv@ "$tmp_env" @envFile@
