{
  imports = [
    ./authentication-checks.nix
    ./cache-checks.nix
    ./checks.nix
    ./configurations.nix
    ./fonts.nix
    ./formatter.nix
    ./generated-config-checks.nix
    ./git-hooks.nix
    ./git-privacy-checks.nix
    ./javascript-checks.nix
    ./local-control-checks.nix
    ./memory-checks.nix
    ./noogle-checks.nix
    ./platform-checks.nix
    ./python-checks.nix
    ./shell.nix
    ./storage-checks.nix
    ./theme-checks.nix
    ./temporary-fix-checks.nix
  ];
}
