options kvm_amd nested=1
# The board uses a Nuvoton NCT6687D-R. The upstream nct6683 driver supports
# it, but requires force=1 on non-Intel boards.
options nct6683 force=1
options cfg80211 ieee80211_regdom=US
